apiVersion: v1
kind: ServiceAccount
metadata:
  name: devguard-k8s-image-inventory
  namespace: devguard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devguard-k8s-image-inventory
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devguard-k8s-image-inventory
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devguard-k8s-image-inventory
subjects:
- kind: ServiceAccount
  name: devguard-k8s-image-inventory
  namespace: devguard
