# .github/workflows/devguard.yml
name: DevGuard Workflow

on:
  push:
 
jobs:
    call-devsecops:
        uses: l3montree-dev/devguard-action/.github/workflows/full.yml@main
        with:
            asset-name: "l3montree-cybersecurity/projects/devguard/assets/devguard-operator"
            api-url: "https://api.main.devguard.org"
            web-ui: "https://main.devguard.org"
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" 
